

bis:
	g++ bisection.cpp -o bis

fp:
	g++ fixedpoint.cpp -o fp

nt:
	g++ newtons.cpp -o nt

sec:
	g++ secant.cpp -o sec

de:	
	g++ derivatives.cpp -o de

int:
	g++ int.cpp -o int

diffy:
	g++ diffy.cpp -o di

dif:
	g++ diffy2.cpp -o d

clean: 
	rm bis fp nt sec de int di d
